inference_timeframes:
  use_custom_ranges: true
  ranges:
    # FOR LIVE INFERENCE
    # - begin: '2025-01-01'
    #   end: '2026-03-01'
    # FOR BENCHMARK
    - begin: '2025-01-01'
      end: '2025-12-01'
    - begin: '2024-01-01'
      end: '2024-12-01'
    - begin: '2023-01-01'
      end: '2023-12-01'
per_lag_modeling:
  chain_ladder: false
  neural_network: true
ibnr_standalone:
  model_types:
    chain_ladder:
      model_configs:
        - occurrence_date_col: "treatment_date"
      segmentation_combinations:
      - - benefit_macro
        - network
      targets:
      - ultimate_amount_paid
      nb_training_years:
      - 1
      - 3
      - 4
      - 5
      input_features_combinations:
      - - cumulative_amount_paid
      - - cumulative_amount_paid
        - treatment_date_month
    neural_network:
      model_configs:
      - unit_per_layer:
        - 32
        - 16
        activation: relu
        learning_rate: 0.01
        epochs: 300
        batch_size: 2000
        loss: huber
      segmentation_combinations:
      - - benefit_macro
        - network
      nb_training_years:
      - 3
      - 4
      - 5
      targets:
      - ultimate_nb_invoice_paid
      - ultimate_nb_claim_paid
      - ultimate_amount_paid
      input_features_combinations:
      - - treatment_date_month
        - cumulative_amount_paid
        - cumulative_nb_claim_paid
        - cumulative_nb_invoice_paid
        - avg_processing_time_w1
        - avg_processing_time_w2
        - avg_processing_time_w3
        - avg_processing_time_w4
ibnr_inflation:
  model_types:
    chain_ladder:
      model_configs:
        - occurrence_date_col: "treatment_date"
      segmentation_combinations:
      - - benefit_macro
        - glm_group
        - network
      targets:
      - ultimate_amount_paid
      nb_training_years:
      - 5
      input_features_combinations:
      - - cumulative_amount_paid
        - treatment_date_month