# Auto-generated by generate_contract.py — do not edit manually.

import gc
import logging
from collections.abc import Callable  # type: ignore # noqa
from typing import Any
import numpy as np  # type: ignore # noqa
import pandas as pd  # type: ignore # noqa
import psutil  # type: ignore # noqa
from joblib import Parallel, delayed  # type: ignore # noqa
from sklearn.base import BaseEstimator, RegressorMixin  # type: ignore # noqa
from datetime import datetime
from dateutil.relativedelta import relativedelta  # type: ignore # noqa
from prophet import Prophet  # type: ignore # noqa
import mlflow
from databricks_mlops_stack.training.model.model_contract import ModelContract  # type: ignore # noqa
import databricks_mlops_stack  # type: ignore # noqa
from pathlib import Path  # type: ignore # noqa
from tempfile import TemporaryDirectory  # type: ignore # noqa
import gc  # type: ignore # noqa

# ────────────────────────────────────────────────────────────────────
# Inlined from multi_cluster_wrapper.py
# ────────────────────────────────────────────────────────────────────
logger = logging.getLogger(__name__)


class MultiClusterWrapper(BaseEstimator, RegressorMixin):
    """
    Trains and serves one internal model per unique combination of
    `segment_columns`, producing a single sklearn-compatible artefact.

    Parameters
    ----------
    numerical_features : list[str]
        Feature columns used for training/prediction.
    segment_columns : list[str]
        Columns whose cross-product defines the segments.
    model_factory : Callable
        A callable with signature:
            model_factory(config, random_state, base_params, extra_params)
                -> fitted-able sklearn-compatible estimator
        Called once per segment during fit() to construct the internal model.
        Example: _build_tf_segment_model from tf_model.py.
    is_tensorflow : bool
        Set to True when model_factory produces TensorFlow-backed models.
        Enables TF-specific optimisations during predict:
          - tf.config.run_functions_eagerly(False)
          - input conversion to tf.constant before predict
          - keras.backend.clear_session() after all segments are fitted
    config : dict
        Either:
        1) a single model config forwarded to every segment, or
        2) a dict where keys are segment ids and values are per-segment configs.
    random_state : int
        Forwarded to model_factory.
    base_params : dict
        Forwarded to model_factory.
    extra_params : dict
        Forwarded to model_factory.
    n_jobs : int
        Number of parallel workers used during fit (-1 = all cores).
    """

    def __init__(
        self,
        numerical_features: list[str],
        segment_columns: list[str],
        model_factory: Callable,
        is_tensorflow: bool,
        config: dict[str, Any],
        random_state: int,
        base_params: dict,
        extra_params: dict,
        n_jobs: int,
    ):
        self.numerical_features = numerical_features or []
        self.segment_columns = segment_columns or []
        self.model_factory = model_factory
        self.is_tensorflow = is_tensorflow
        self.config = config or {}
        self.random_state = random_state
        self.base_params = base_params or {}
        self.extra_params = extra_params or {}
        self.n_jobs = n_jobs

        # Populated by fit()
        self.models_: dict[tuple, Any] = {}
        self.target_column_: str | None = None
        self.number_clusters: int = -1

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _cluster_key(key) -> tuple:
        """Normalise a groupby key to a hashable tuple."""
        return key if isinstance(key, tuple) else (key,)

    @staticmethod
    def _cluster_key_aliases(key: tuple) -> list[str]:
        aliases = {str(key)}
        aliases.add("__".join(str(x) for x in key))
        if len(key) == 1:
            aliases.add(str(key[0]))
        return [x for x in aliases if x]

    @staticmethod
    def _looks_like_segment_config_map(cfg: dict[str, Any]) -> bool:
        if not cfg:
            return False
        return all(isinstance(v, dict) for v in cfg.values())

    def _resolve_config_for_segment(self, key: tuple) -> dict[str, Any]:
        cfg = self.config if isinstance(self.config, dict) else {}
        if not self._looks_like_segment_config_map(cfg):
            return cfg

        for alias in self._cluster_key_aliases(key):
            maybe_cfg = cfg.get(alias)
            if isinstance(maybe_cfg, dict):
                return maybe_cfg

        logger.warning("No per-segment config found for key %s; using empty config.", key)
        return {}

    def _fit_one_cluster(
        self,
        key: tuple,
        X: pd.DataFrame,
        y: pd.Series,
    ) -> tuple[tuple, Any]:
        """Build and fit a single cluster model; designed for parallel use."""
        resolved_config = self._resolve_config_for_segment(key)
        model = self.model_factory(
            resolved_config,
            self.random_state,
            self.base_params,
            self.extra_params,
        )
        # Optional hook for models that need cluster-aware runtime config.
        if hasattr(model, "set_cluster_key"):
            model.set_cluster_key(key)
        elif hasattr(model, "named_steps"):
            maybe_step_model = model.named_steps.get("model")
            if hasattr(maybe_step_model, "set_cluster_key"):
                maybe_step_model.set_cluster_key(key)
        model.fit(X, y)
        logger.info(f"Finished fitting cluster: {key}")
        return key, model

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def fit(self, df: pd.DataFrame, y: pd.Series | str) -> "MultiClusterWrapper":
        """
        Fit one internal model per unique combination of `segment_columns`.

        Parameters
        ----------
        df : pd.DataFrame
            Full training dataframe. Must contain `segment_columns`,
            `numerical_features`, and the target column.
        y : pd.Series or str
            Target values, or the name of the target column in `df`.

        Returns
        -------
        self
        """
        if self.model_factory is None:
            raise ValueError("model_factory must be provided before calling fit().")

        if isinstance(y, str):
            target = df[y]
            self.target_column_ = y
        else:
            target = y
            self.target_column_ = target.name

        missing_seg = [c for c in self.segment_columns if c not in df.columns]
        if missing_seg:
            raise ValueError(f"segment columns not found in df: {missing_seg}")

        missing_feat = [c for c in self.numerical_features if c not in df.columns]
        if missing_feat:
            raise ValueError(f"Numerical features not found in df: {missing_feat}")

        groups = list(df.groupby(self.segment_columns, sort=False))
        logger.info("Fitting %d cluster models with n_jobs=%d …", len(groups), self.n_jobs)

        results: list[tuple[tuple, Any]] = Parallel(n_jobs=self.n_jobs, prefer="threads")(
            delayed(self._fit_one_cluster)(
                self._cluster_key(key),
                group[self.numerical_features],
                target.loc[group.index],
            )
            for key, group in groups
        )

        self.models_ = dict(results)
        self.number_clusters = len(self.models_)
        logger.info("Fitting complete. Clusters stored: %d", len(self.models_))

        # TF-specific: clear Keras session state accumulated during training.
        # Safe to call here because all models are already fitted and stored;
        # none rely on a persistent Keras session after fit() completes.
        if self.is_tensorflow:
            try:
                from tensorflow import keras  # type: ignore[import-untyped]

                keras.backend.clear_session()
                logger.info("Keras backend session cleared after fitting.")
            except Exception as exc:  # noqa: BLE001
                logger.warning("Could not clear Keras session: %s", exc)

        gc.collect()

        return self

    def predict(self, df: pd.DataFrame) -> np.ndarray:
        """
        Generate predictions for all rows in `df`.

        Rows are grouped by `segment_columns`; each group is dispatched to
        the corresponding fitted cluster model. The original row order is
        preserved in the returned array.

        Parameters
        ----------
        df : pd.DataFrame
            Must contain `segment_columns` and `numerical_features`.
            May contain any subset of the clusters seen during fit.

        Returns
        -------
        predictions : np.ndarray of shape (n_samples,)

        Raises
        ------
        RuntimeError
            If the model has not been fitted yet.
        KeyError
            If a cluster in `df` was not seen during fit.
        ValueError
            If required columns are missing from `df`.
        """
        if not self.models_:
            raise RuntimeError("MultiClusterWrapper is not fitted yet. Call fit() first.")

        missing_seg = [c for c in self.segment_columns if c not in df.columns]
        if missing_seg:
            raise ValueError(f"segment columns not found in df: {missing_seg}")

        # TF-specific: ensure graph mode is active to reduce retracing.
        if self.is_tensorflow:
            try:
                import tensorflow as tf  # type: ignore[import-untyped]

                tf.config.run_functions_eagerly(False)
            except Exception as exc:  # noqa: BLE001
                logger.warning("Could not set TF eager mode: %s", exc)

        process = psutil.Process()
        predictions = pd.Series(index=df.index, dtype=float)

        if self.is_tensorflow:
            import tensorflow as tf  # type: ignore[import-untyped]

        for key, group in df.groupby(self.segment_columns, sort=False):
            seg_key = self._cluster_key(key)

            if seg_key not in self.models_:
                raise KeyError(f"Cluster {seg_key} was not seen during training. Cannot generate predictions for unseen clusters.")

            X = group[self.numerical_features]

            preds = self.models_[seg_key].predict(X)
            predictions.loc[group.index] = preds

            mem_gb = process.memory_info().rss / 1024**3
            logger.info("segment %s — Memory: %.2f GB", seg_key, mem_gb)

        gc.collect()

        # Restore original row order
        return predictions.loc[df.index].values

    def compact_for_serialization(self) -> None:
        """Best-effort memory compaction before pickling/logging."""
        for maybe_estimator in self.models_.values():
            if hasattr(maybe_estimator, "prepare_for_serialization"):
                try:
                    maybe_estimator.prepare_for_serialization()
                except Exception:
                    pass
            named_steps = getattr(maybe_estimator, "named_steps", None)
            if isinstance(named_steps, dict):
                step_model = named_steps.get("model")
                if step_model is not None and hasattr(step_model, "prepare_for_serialization"):
                    try:
                        step_model.prepare_for_serialization()
                    except Exception:
                        pass
            for nested_attr in ("regressor", "regressor_", "estimator", "estimator_"):
                nested = getattr(maybe_estimator, nested_attr, None)
                if nested is None:
                    continue
                nested_steps = getattr(nested, "named_steps", None)
                if isinstance(nested_steps, dict):
                    nested_model = nested_steps.get("model")
                    if nested_model is not None and hasattr(nested_model, "prepare_for_serialization"):
                        try:
                            nested_model.prepare_for_serialization()
                        except Exception:
                            pass
        gc.collect()


# ────────────────────────────────────────────────────────────────────
# Inlined from inflation_prophet.py
# ────────────────────────────────────────────────────────────────────
LOG = logging.getLogger(__name__)


class ProphetModel(BaseEstimator, RegressorMixin):
    def __init__(
        self,
        config: dict[str, Any],
        random_state: int,
        params: dict,
        extra_params: dict,
    ) -> None:
        self.config = config or {}
        self.random_state = random_state
        self.params = params or {}
        self.extra_params = extra_params or {}

        self.feature_columns: list[str] = list(self.extra_params.get("feature_columns", []))
        self.temporal_column: str = str(self.extra_params.get("temporal_reference_column", "ds"))

        self._cluster_key: tuple | None = None
        self._active_model_config: dict[str, Any] = {}
        self._regressors: list[str] = []
        self.model: Prophet | None = None

    def set_cluster_key(self, key: tuple) -> None:
        self._cluster_key = key

    def _cluster_key_aliases(self) -> list[str]:
        if self._cluster_key is None:
            return []
        raw = self._cluster_key if isinstance(self._cluster_key, tuple) else (self._cluster_key,)
        aliases = {
            str(self._cluster_key),
            str(raw),
            "__".join(str(x) for x in raw),
        }
        if len(raw) == 1:
            aliases.add(str(raw[0]))
        return list(aliases)

    def _resolve_model_config(self) -> dict[str, Any]:
        base = self.config if isinstance(self.config, dict) else {}
        resolved: dict[str, Any] = {}

        default_cfg = base.get("default_model_config")
        if isinstance(default_cfg, dict):
            resolved.update(default_cfg)

        cluster_map = base.get("cluster_model_config_map")
        if isinstance(cluster_map, dict):
            for alias in self._cluster_key_aliases():
                maybe_cluster_cfg = cluster_map.get(alias)
                if isinstance(maybe_cluster_cfg, dict):
                    resolved.update(maybe_cluster_cfg)
                    break

        for k, v in base.items():
            if k in {"default_model_config", "cluster_model_config_map"}:
                continue
            resolved.setdefault(k, v)

        return resolved

    def _to_feature_dataframe(self, x: pd.DataFrame | np.ndarray) -> pd.DataFrame:
        if isinstance(x, pd.DataFrame):
            df = x.copy()
        else:
            arr = np.asarray(x)
            if arr.ndim == 1:
                arr = arr.reshape(-1, 1)
            if self.feature_columns and len(self.feature_columns) == arr.shape[1]:
                cols = self.feature_columns
            else:
                cols = [f"feature_{i}" for i in range(arr.shape[1])]
            df = pd.DataFrame(arr, columns=cols)

        if self.temporal_column not in df.columns:
            raise ValueError(
                f"Temporal column '{self.temporal_column}' not found in features. "
                f"Columns: {list(df.columns)}"
            )

        df[self.temporal_column] = pd.to_datetime(df[self.temporal_column], errors="coerce")
        if df[self.temporal_column].isna().any():
            raise ValueError(f"Temporal column '{self.temporal_column}' contains invalid dates")

        return df.reset_index(drop=True)

    def _build_prophet(self, model_cfg: dict[str, Any], df: pd.DataFrame) -> Prophet:
        changepoint_nb_months_censored = int(model_cfg.get("changepoint_nb_months_censored", 0) or 0)
        changepoint_nb_per_year = model_cfg.get("changepoint_nb_per_year")
        n_changepoints = model_cfg.get("n_changepoints")
        if n_changepoints is None and changepoint_nb_per_year:
            max_date = df[self.temporal_column].max()
            min_date = df[self.temporal_column].min()
            if isinstance(max_date, datetime) and isinstance(min_date, datetime):
                effective_max = max_date - relativedelta(months=changepoint_nb_months_censored)
                total_nb_months = (effective_max.year - min_date.year) * 12 + (effective_max.month - min_date.month) + 1
                total_nb_months = max(1, total_nb_months)
                n_changepoints = int(float(changepoint_nb_per_year) * total_nb_months / 12)

        prophet_kwargs = {
            "yearly_seasonality": bool(model_cfg.get("yearly_seasonality", False)),
            "weekly_seasonality": bool(model_cfg.get("weekly_seasonality", False)),
            "daily_seasonality": bool(model_cfg.get("daily_seasonality", False)),
            "changepoint_range": float(model_cfg.get("changepoint_range", 1.0)),
            "changepoint_prior_scale": float(model_cfg.get("changepoint_prior_scale", 0.05)),
        }
        if n_changepoints is not None:
            prophet_kwargs["n_changepoints"] = int(n_changepoints)

        model = Prophet(**prophet_kwargs)

        seasonality_period = model_cfg.get("seasonality_period")
        seasonality_fourier_order = model_cfg.get("seasonality_fourier_order")
        if seasonality_period and seasonality_fourier_order:
            model.add_seasonality(
                name="custom_seasonality",
                period=float(seasonality_period),
                fourier_order=int(seasonality_fourier_order),
            )

        country_holidays = model_cfg.get("country_holidays")
        if country_holidays:
            model.add_country_holidays(country_name=str(country_holidays))

        regressors = model_cfg.get("regressors")
        self._regressors = []
        if isinstance(regressors, dict):
            for regressor_name, prior_scale in regressors.items():
                kwargs: dict[str, Any] = {}
                try:
                    kwargs["prior_scale"] = float(prior_scale)
                except Exception:
                    pass
                model.add_regressor(str(regressor_name), **kwargs)
                self._regressors.append(str(regressor_name))

        return model

    def fit(
        self,
        x: pd.DataFrame | np.ndarray,
        y: pd.Series | np.ndarray,
        **extra_params,
    ) -> "ProphetModel":
        _ = extra_params
        df = self._to_feature_dataframe(x)
        target = pd.Series(y).reset_index(drop=True)

        if len(df) != len(target):
            raise ValueError(f"X/y length mismatch ({len(df)} != {len(target)})")

        model_cfg = self._resolve_model_config()
        self._active_model_config = model_cfg
        self.model = self._build_prophet(model_cfg, df)

        prophet_df = pd.DataFrame(
            {
                "ds": df[self.temporal_column],
                "y": pd.to_numeric(target, errors="coerce"),
            }
        )
        for regressor in self._regressors:
            if regressor not in df.columns:
                raise ValueError(
                    f"Regressor '{regressor}' declared in config but missing from features. "
                    f"Columns: {list(df.columns)}"
                )
            prophet_df[regressor] = pd.to_numeric(df[regressor], errors="coerce")

        months_censored = int(model_cfg.get("changepoint_nb_months_censored", 0) or 0)
        if months_censored > 0:
            cutoff_date = prophet_df["ds"].max() - relativedelta(months=months_censored)
            prophet_df.loc[prophet_df["ds"] > cutoff_date, "y"] = None

        self.model.fit(prophet_df)
        return self

    def predict(
        self,
        x: pd.DataFrame | np.ndarray,
    ) -> np.ndarray:
        if self.model is None:
            raise RuntimeError("ProphetModel must be fitted before predict().")

        df = self._to_feature_dataframe(x)
        future = pd.DataFrame({"ds": df[self.temporal_column]})
        for regressor in self._regressors:
            if regressor not in df.columns:
                raise ValueError(
                    f"Regressor '{regressor}' declared in config but missing from prediction features."
                )
            future[regressor] = pd.to_numeric(df[regressor], errors="coerce")

        forecast = self.model.predict(future)
        if "yhat" not in forecast.columns:
            raise ValueError("Prophet forecast does not contain 'yhat'")
        return pd.to_numeric(forecast["yhat"], errors="coerce").fillna(0.0).to_numpy(dtype=float)


def _build_cluster_model(
    config: dict,
    random_state: int,
    base_params: dict,
    extra_params: dict,
) -> ProphetModel:
    _ = base_params
    return ProphetModel(
        config=config,
        random_state=random_state,
        params=base_params,
        extra_params=extra_params,
    )


# ────────────────────────────────────────────────────────────────────
# Inlined from model_contract_template.py
# ────────────────────────────────────────────────────────────────────
# ── Model configuration ──────────────────────────────────────────── #

_NUMERICAL_FEATURES: list[str] = ['year_month_date', 'cluster_id']

_SEGMENT_COLUMNS: list[str] = ['cluster_id']

_CONFIG: dict = {'default_model_config': {}, 'cluster_model_config_map': {}}

_RANDOM_STATE: int = 42

_BASE_PARAMS: dict = {'random_state': 42}

_EXTRA_PARAMS: dict = {'random_state': 42, 'feature_columns': ['year_month_date', 'cluster_id'], 'temporal_reference_column': 'year_month_date', 'segment_column': 'cluster_id'}

_N_JOBS: int = -1

_IS_TENSORFLOW: bool = False

_FACTORY_FN = _build_cluster_model


# ── Contract implementation ──────────────────────────────────────── #

class ModelContractImpl(ModelContract):

    def get_model(self, args: dict[str, Any]):
        model = MultiClusterWrapper(
            numerical_features=_NUMERICAL_FEATURES,
            segment_columns=_SEGMENT_COLUMNS,
            model_factory=_FACTORY_FN,
            is_tensorflow=_IS_TENSORFLOW,
            config=_CONFIG,
            random_state=_RANDOM_STATE,
            base_params=_BASE_PARAMS,
            extra_params=_EXTRA_PARAMS,
            n_jobs=_N_JOBS,
        )
        return model

    def log_model(
        self,
        model,
        model_name,
        signature,
        input_example,
        args: dict[str, Any],
    ):
        if hasattr(model, "compact_for_serialization"):
            try:
                model.compact_for_serialization()
            except Exception:
                pass
        gc.collect()
        mlflow.sklearn.log_model(
            model,
            artifact_path="model",
            registered_model_name=model_name,
            signature=signature,
            input_example=input_example,
        )

    #     gc.collect()

    #     package_dir = Path(databricks_mlops_stack.__file__).resolve().parent
    #     code_paths = [str(package_dir)]
 
    #     # Build a temporary local model first and reuse the exact requirements inferred by MLflow there.
    #     # Then remove only the private framework package that serving cannot install from public indexes.
    #     default_reqs, inferred = self.get_infer_mlflow_dependencies(code_paths, input_example, model, signature)
 
    #     filtered = [r for r in inferred if not str(r).lower().startswith("databricks-mlops-stack")]
    #     # Preserve order while removing duplicates.
    #     filtered = list(dict.fromkeys(filtered))
    #     if not filtered:
    #         filtered = default_reqs
 
    #     mlflow.sklearn.log_model(
    #         model,
    #         artifact_path="model",
    #         registered_model_name=model_name,
    #         signature=signature,
    #         input_example=input_example,
    #         code_paths=code_paths,
    #         pip_requirements=filtered,
    #     )
        
    # def get_infer_mlflow_dependencies(self, code_paths: list[str], input_example, model, signature) -> tuple[list[str], list[str]]:
    #     default_reqs = mlflow.sklearn.get_default_pip_requirements()
    #     try:
    #         with TemporaryDirectory(prefix="mlflow-model-reqs-") as tmp_dir:
    #             local_model_path = str(Path(tmp_dir) / "model")
    #             mlflow.sklearn.save_model(
    #                 sk_model=model,
    #                 path=local_model_path,
    #                 signature=signature,
    #                 input_example=input_example,
    #                 code_paths=code_paths,
    #             )
    #             gc.collect()
    #             inferred: list[str] = []
    #             req_file = Path(local_model_path) / "requirements.txt"
    #             if req_file.exists():
    #                 for line in req_file.read_text(encoding="utf-8").splitlines():
    #                     dep = line.strip()
    #                     if not dep or dep.startswith("#"):
    #                         continue
    #                     inferred.append(dep)
    #             if not inferred:
    #                 inferred = list(
    #                     mlflow.models.infer_pip_requirements(
    #                         model_uri=local_model_path,
    #                         flavor="sklearn",
    #                         fallback=default_reqs,
    #                     )
    #                 )
    #     except Exception:
    #         inferred = default_reqs
    #     return default_reqs, inferred


build = ModelContractImpl()
