catalog: 'axainsurance_claims_dv_ml'
schema: 'sanity_build'
table_name: 'sanity_build_fs'
feature_columns:
  - subscription_length
  - vehicle_age
  - customer_age
  - segment
  - is_esc
target_column : claim_status
return_dataframe_type: pandas
temporal_reference_column: claim_date
enable_baseline_table: true